export default {
  colors: {
    primary: '#2B2D42',
    secondary: '#1D1F2A',
    background: '#0B0C10',
    accent: '#1FA1B8',
    black: '#000000',
    white: '#E5E5E5',
    gray: '#A9A9A9',
    error: '#FF4136',
    success: '#2ECC40',
  },
  shadows: {
    light: 1,
    medium: 10,
    heavy: 15,
    veryHeavy: 20,
    huge: 30,
  },
  fonts: {
    default: 'Latinka Regular',
    italic: 'Latinka Italic',
    black: 'Latinka Black',
    blackItalic: 'Latinka Black Italic',
    extraBold: 'Latinka ExtraBold',
    extraBoldItalic: 'Latinka ExtraBold Italic',
    bold: 'Latinka Bold',
    boldItalic: 'Latinka Bold Italic',
    semiBold: 'Latinka SemiBold',
    semiBoldItalic: 'Latinka SemiBold Italic',
    medium: 'Latinka Medium',
    mediumItalic: 'Latinka Medium Italic',
    light: 'Latinka Light',
    lightItalic: 'Latinka Light Italic',
    thin: 'Latinka Thin',
    thinItalic: 'Latinka Thin Italic',
  },
};
