export const emptyReadingMessages = [
  "Your manga shelf is as empty as a ninja's footprint... time to change that!",
  "No stories here. Did Thanos snap your reading list?",
  "Even Goku takes breaks—but this one's too long. Add a manga!",
  "No manga, no life. Your list is craving some action!",
  "Like a shounen protagonist with no backstory… your list is tragically empty.",
  "Plot twist: there's no plot! Find a manga to start your arc.",
  "Nothing here… not even a filler episode.",
  "Your list is more deserted than a post-apocalyptic Tokyo.",
  "A wild manga has not appeared! Quick, go catch one!",
  "This space is so empty, even L couldn't find a clue.",
  "Looks like your manga radar is off. Time to recalibrate!",
  "Not a single panel in sight. Let's fix that.",
  "No villains, no heroes… just an empty void. Add something!",
  "Your adventure hasn't begun yet. Time to turn the first page!",
  "Is this... a slice of life about not reading anything?",
  "No drama. No comedy. Not even a tragic backstory. Just... nothing.",
  "You're one scroll away from your next obsession.",
  "An empty list? That's not very shōnen of you.",
  "No reading today? Even Light had a book with names.",
  "The only thing missing is… well, everything.",
  "This space is so empty it could be a new isekai world.",
  "A blank list—a perfect place for your next guilty pleasure.",
  "Even One Piece started with just one chapter. Begin yours now!",
  "Like a mangaka with no deadline—absolutely nothing here.",
  "Every great story starts somewhere. This could be it!",
  "Your list is quieter than a stealth mission in a ninja village.",
  "Cue the sad piano music… nothing to read yet.",
  "You've reached Zen: the art of having no manga to read.",
  "No chapters, no cliffhangers, just a peaceful void.",
  "This feels more filler than canon. Time for a real series!",
];
